tools:
  - python: 3.10

docker:
  - name: 'python-agent'
    image: 'docker.ci.artifacts.walmart.com/devtools-docker/looper/looper-python-agent:3.10'

envs:
  global:
    variables:
      ALLOW_ARTIFACTORY: true

rules:
  before:
    - var(BRANCH_NAME):
        '%{TRIGGER_BRANCH.replaceAll(".+/","")}'
    - var(BRANCH_NAME_LOWERCASE):
        '%{BRANCH_NAME.toLowerCase()}'
    - var(COMMIT_USER): git log -1 --format="%aN"

flows:
  default:
    - call: releaseFlow

  releaseFlow:
    try:
      - node(docker-daemon):
          - dockerAgent(python-agent):
              - call: releaseSteps
    catch:
      - fail('Error performing Release Flow - $flowErrorMessage')

  releaseSteps:
    - shell: |
        python -m pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/* --verbose